version: '3.8'

services:
  app:
    container_name: app-dev
    ports:
      - 3000:3000
    image: ${DOCKER_REGISTRY-}react-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev